### ISSUE TITLE
Realizar en la versión de JAVA 11 para la corrección

### ISSUE THREAD

**Issue by nightpablo** [franciscocaloia/taller02#1]
No se puede evaluar una versión superior a 11, es necesario que lo migres a la versión 11 y, de paso, completarlo.

**Comment by franciscocaloia** [comment]
Hola profe, qué sería lo que debemos completar?

**Comment by nightpablo** [comment]
Lo escribia por si faltaba completarlo y tenian tiempo para corregirlo, pero si no tienen nada que corregir, con eso ya esta.
La idea es que lo migren a la version 11 de Java como vinimos haciendo desde el principio de la cátedra.

**Comment by franciscocaloia** [comment]
Listo profe, el trabajo ya se encuentra en la versión java 11

**Comment by nightpablo** [comment]
Aprobado
